name: Add to Project (GraphQL)

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add item to project
        env:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
          PROJECT_ID: "PVT_kwDOBPETM84BFckh"
          ITEM_ID: ${{ github.event.issue.node_id || github.event.pull_request.node_id }}
        run: |
          gh api graphql -f query='
            mutation($project:ID!, $item:ID!) {
              addProjectV2ItemById(input: {projectId: $project, contentId: $item}) {
                item {
                  id
                }
              }
            }
          ' -f project=$PROJECT_ID -f item=$ITEM_ID
