name: Auto-label Service
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Add service label
        uses: actions/github-script@v7
        with:
          script: |
            const serviceLabel = 'service:cqvx';
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [serviceLabel]
            });
